### ISSUE TITLE
Tạo component ô Sản phẩm hiên trên gian hàng

### ISSUE THREAD

**Issue by lamnguyen13052003** [lamnguyen13052003/lt_front_end_thuong_mai_dien_tu#4]
![image](https://github.com/lamnguyen13052003/lt_front_end_thuong_mai_dien_tu/assets/145332211/8f3d5c9e-b432-4ec6-9a3c-f9f318ca37b3)

**Comment by LamHongPhong1401** [comment]
![image](https://github.com/lamnguyen13052003/lt_front_end_thuong_mai_dien_tu/assets/128471861/25aef212-030a-4c4d-a854-dce10523f93f)
đã hoàn thành theo yêu cầu.

**Comment by lamnguyen13052003** [comment]
Tốt lắm con zai
